create database minecraft;
use minecraft;

create table tb_world (
	id int primary key auto_increment,
    name varchar(255) unique not null
);

create table tb_player (
	id int primary key auto_increment,
    name varchar(255) unique not null
);

create table tb_shop_item (
	first_id int not null,
    second_id int not null,
    name varchar(255) not null,
    english_name varchar(255) not null,
    price int not null,
    group_amount int not null,
    primary key (first_id, second_id)
);

create table tb_shop_record (
	id int primary key auto_increment,
    player_id int not null,
    world_id int not null,
    item_first_id int not null,
    item_second_id int not null,
    amount int not null,
    type int not null,
    time timestamp not null,
    foreign key (player_id) references tb_player(id),
    foreign key (world_id) references tb_world(id),
    foreign key (item_first_id, item_second_id) references tb_shop_item(first_id, second_id)
);

create table tb_bank_account (
	id int primary key auto_increment,
    player_id int not null,
    world_id int not null,
    balance int not null,
    foreign key (player_id) references tb_player(id),
	foreign key (world_id) references tb_world(id)
);

create table tb_bank_account_record (
	id int primary key auto_increment,
    src int not null,
    dest int not null,
    amount double not null,
    time timestamp not null,
    note varchar(255),
    foreign key (src) references tb_bank_account(id),
    foreign key (dest) references tb_bank_account(id)
);

insert into tb_world (id, name) values (0, 'default');
insert into tb_player (id, name) values (0, 'admin');
insert into tb_bank_account (id, player_id, world_id, balance) values (0, 0, 0, 0);

/*
-- Query: select * from tb_minecraft_item
LIMIT 0, 1000

-- Date: 2017-10-14 20:47
*/
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (1,0,'石头','stone',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (1,1,'花岗岩','stone',5500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (1,2,'磨制花岗岩','stone',5750,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (1,3,'闪长岩','stone',3500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (1,4,'磨制闪长岩','stone',3600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (1,5,'安山岩','stone',3600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (1,6,'磨制安山岩','stone',3750,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (2,0,'草方块','grass',20,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (3,0,'泥土','dirt',10,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (3,1,'砂土','dirt',30,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (3,2,'灰化土','dirt',30,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (4,0,'圆石','cobblestone',40,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (5,0,'橡木木板','planks',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (5,1,'云杉木板','planks',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (5,2,'白桦木板','planks',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (5,3,'丛林木板','planks',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (5,4,'金合欢木板','planks',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (5,5,'深色橡木木板','planks',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (6,0,'橡树树苗','sapling',1250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (6,1,'云杉树苗','sapling',1250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (6,2,'白桦树苗','sapling',1250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (6,3,'丛林树苗','sapling',1250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (6,4,'金合欢树苗','sapling',1250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (6,5,'深色橡树树苗','sapling',1250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (7,0,'基岩','bedrock',2000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (12,0,'沙子','sand',30,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (12,1,'红沙','sand',40,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (13,0,'砂砾','gravel',40,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (14,0,'金矿石','gold_ore',600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (15,0,'铁矿石','iron_ore',400,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (16,0,'煤矿石','coal_ore',250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (17,0,'橡木','log',160,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (17,1,'云杉木','log',160,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (17,2,'白桦木','log',160,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (17,3,'丛林木','log',160,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (18,0,'橡树树叶','leaves',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (18,1,'云杉树叶','leaves',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (18,2,'白桦树叶','leaves',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (18,3,'丛林树叶','leaves',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (19,0,'海绵','sponge',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (19,1,'湿海绵','sponge',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (20,0,'玻璃','glass',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (21,0,'青金石矿石','lapis_ore',800,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (22,0,'青金石块','lapis_block',1800,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (23,0,'发射器','dispenser',720,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (24,0,'沙石','sandstone',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (24,1,'錾制沙石','sandstone',180,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (24,2,'平滑沙石','sandstone',180,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (25,0,'音符盒','noteblock',600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (27,0,'动力铁轨','golden_rail',800,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (28,0,'探测铁轨','detecor_rail',600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (29,0,'粘性活塞','sticky_piston',1200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (30,0,'蜘蛛网','web',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (31,0,'灌木','tallgrass',60,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (31,1,'草','tallgrass',60,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (31,2,'蕨','tallgrass',60,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (32,0,'枯死的灌木','deadbush',60,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (33,0,'活塞','piston',1000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (35,0,'羊毛','wool',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (35,1,'橙色羊毛','wool',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (35,2,'品红色羊毛','wool',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (35,3,'淡蓝色羊毛','wool',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (35,4,'黄色羊毛','wool',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (35,5,'黄绿色羊毛','wool',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (35,6,'粉红色羊毛','wool',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (35,7,'灰色羊毛','wool',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (35,8,'淡灰色羊毛','wool',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (35,9,'青色羊毛','wool',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (35,10,'紫色羊毛','wool',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (35,11,'蓝色羊毛','wool',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (35,12,'棕色羊毛','wool',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (35,13,'绿色羊毛','wool',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (35,14,'红色羊毛','wool',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (35,15,'黑色羊毛','wool',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (37,0,'蒲公英','yellow_flower',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (38,0,'罂粟','red_flower',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (38,1,'兰花','red_flower',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (38,2,'绒球葱','red_flower',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (38,3,'茜草花','red_flower',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (38,4,'红色郁金香','red_flower',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (38,5,'橙色郁金香','red_flower',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (38,6,'白色郁金香','red_flower',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (38,7,'粉红色郁金香','red_flower',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (38,8,'滨菊','red_flower',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (39,0,'蘑菇','brown_mushroom',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (40,0,'蘑菇','red_mushroom',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (41,0,'金块','gold_block',7200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (42,0,'铁块','iron_block',4500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (44,0,'石台阶','stone_slab',60,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (44,1,'沙石台阶','stone_slab',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (44,3,'圆石台阶','stone_slab',30,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (44,4,'砖台阶','stone_slab',240,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (44,5,'石砖台阶','stone_slab',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (44,6,'地狱砖台阶','stone_slab',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (44,7,'石英台阶','stone_slab',3500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (45,0,'砖块','brick_block',420,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (46,0,'TNT','tnt',1000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (47,0,'书架','bookshelf',1500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (48,0,'苔石','mossy_cobblestone',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (49,0,'黑曜石','obsidian',400,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (50,0,'火把','torch',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,50,'刷怪箱-爬行者（Creeper）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,51,'刷怪箱-骷髅（Skeleton）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,52,'刷怪箱-蜘蛛（Spider）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,53,'刷怪箱-大僵尸（Giant）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,54,'刷怪箱-僵尸（Zombie）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,55,'刷怪箱-史莱姆（Slime）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,56,'刷怪箱-恶魂（Ghast）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,57,'刷怪箱-僵尸猪人（PigZombie）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,58,'刷怪箱-末影人（Enderman）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,59,'刷怪箱-洞穴蜘蛛（CaveSpider）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,60,'刷怪箱-蠹虫（Silverfish）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,61,'刷怪箱-烈焰人（Blaze）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,62,'刷怪箱-岩浆怪（LavaSlime）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,64,'刷怪箱-凋零（WitherBoss）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,65,'刷怪箱-蝙蝠（Bat）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,66,'刷怪箱-女巫（Witch）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,67,'刷怪箱-末影螨（Endermite）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,68,'刷怪箱-守卫者（Guardian）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,90,'刷怪箱-猪（Pig）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,91,'刷怪箱-羊（Sheep）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,92,'刷怪箱-牛（Cow）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,93,'刷怪箱-鸡（Chicken）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,94,'刷怪箱-鱿鱼（Squid）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,95,'刷怪箱-狼（Wolf）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,96,'刷怪箱-哞菇（MushroomCow）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,97,'刷怪箱-雪傀儡（SnowMan）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,98,'刷怪箱-豹猫（Ozelot）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,99,'刷怪箱-铁傀儡（VillagerGolem）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,100,'刷怪箱-马（EntityHorse）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,101,'刷怪箱-兔子（Rabbit）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (52,120,'刷怪箱-村民（Villager）','mob_spawner',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (53,0,'橡木楼梯','oak_stairs',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (54,0,'箱子','chest',450,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (56,0,'钻石矿石','diamond_ore',1000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (57,0,'钻石块','diamond_block',12000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (58,0,'工作台','crafting_table',250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (60,0,'耕地','farmland',20,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (61,0,'熔炉','furnace',350,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (65,0,'梯子','ladder',240,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (66,0,'铁轨','rail',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (67,0,'石楼梯','stone_stairs',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (69,0,'拉杆','lever',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (70,0,'石质压力板','stone_pressure_plate',240,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (72,0,'木质压力板','wodden_pressure_plate',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (73,0,'红石矿石','redstone_ore',750,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (76,0,'红石火把','redstone_torch',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (77,0,'按钮（石质）','stone_button',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (78,0,'雪','snow_layer',60,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (79,0,'冰','ice',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (80,0,'雪块','snow',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (81,0,'仙人掌','cactus',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (82,0,'粘土块','clay',240,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (84,0,'唱片机','jukebox',1800,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (85,0,'橡木栅栏','fence',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (86,0,'南瓜','pumpkin',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (87,0,'地狱岩','netherrack',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (88,0,'灵魂沙','soul_sand',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (89,0,'萤石','glowstone',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (91,0,'南瓜灯','lit_pumpkin',240,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (95,0,'白色染色玻璃','stained_glass',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (95,1,'橙色染色玻璃','stained_glass',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (95,2,'品红色染色玻璃','stained_glass',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (95,3,'淡蓝色染色玻璃','stained_glass',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (95,4,'黄色染色玻璃','stained_glass',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (95,5,'黄绿色染色玻璃','stained_glass',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (95,6,'粉红色染色玻璃','stained_glass',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (95,7,'灰色染色玻璃','stained_glass',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (95,8,'淡灰色染色玻璃','stained_glass',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (95,9,'青色染色玻璃','stained_glass',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (95,10,'紫色染色玻璃','stained_glass',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (95,11,'蓝色染色玻璃','stained_glass',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (95,12,'棕色染色玻璃','stained_glass',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (95,13,'绿色染色玻璃','stained_glass',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (95,14,'红色染色玻璃','stained_glass',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (95,15,'黑色染色玻璃','stained_glass',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (96,0,'活板门','trapdoor',180,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (97,0,'石头怪物蛋','monster_egg',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (97,1,'圆石怪物蛋','monster_egg',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (97,2,'石砖怪物蛋','monster_egg',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (97,3,'苔石砖怪物蛋','monster_egg',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (97,4,'裂石砖怪物蛋','monster_egg',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (97,5,'錾制石砖怪物蛋','monster_egg',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (98,0,'石砖','stonebrick',160,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (98,1,'苔石砖','stonebrick',240,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (98,2,'裂石砖','stonebrick',240,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (98,3,'錾制石砖','stonebrick',240,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (99,0,'蘑菇','brown_mushroom_block',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (100,0,'蘑菇','red_mushroom_block',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (101,0,'铁栏杆','iron_bars',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (102,0,'玻璃板','glass_pane',40,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (103,0,'西瓜方块','melon_block',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (106,0,'藤蔓','vine',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (107,0,'橡木栅栏门','fence_gate',250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (108,0,'砖楼梯','brick_stairs',650,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (109,0,'石砖楼梯','stone_brick_stairs',270,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (110,0,'菌丝','mycelium',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (111,0,'睡莲','waterlily',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (112,0,'地狱砖块','nether_brick',750,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (113,0,'地狱砖栅栏','nether_brick_fence',800,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (114,0,'地狱砖楼梯','nether_brick_stairs',800,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (116,0,'附魔台','enchanting_table',4500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (120,0,'末地传送门','end_portal_frame',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (121,0,'末地石','end_stone',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (122,0,'龙蛋','dragon_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (123,0,'红石灯','redstone_lamp',1000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (126,0,'橡木台阶','wooden_slab',30,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (126,1,'云杉台阶','wooden_slab',30,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (126,2,'桦木台阶','wooden_slab',30,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (126,3,'丛林台阶','wooden_slab',30,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (126,4,'金合欢木台阶','wooden_slab',30,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (126,5,'深色橡木台阶','wooden_slab',30,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (128,0,'沙石楼梯','sandstone_stairs',240,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (129,0,'绿宝石矿石','emerald_ore',1200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (130,0,'末影箱','ender_chest',4200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (131,0,'拌线钩','tripwire_hook',600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (133,0,'绿宝石块','emerald_block',15000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (134,0,'云杉木楼梯','spruce_stairs',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (135,0,'桦木楼梯','brich_stairs',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (136,0,'丛林木楼梯','jungle_stairs',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (137,0,'命令方块','command_block',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (138,0,'信标','beacon',3200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (139,0,'圆石墙','cobblestone_wall',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (139,1,'苔石墙','cobblestone_wall',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (143,0,'按钮（木质）','wooden_button',60,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (145,0,'铁砧','anvil',16000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (145,1,'轻微损坏的铁砧','anvil',10000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (145,2,'严重损坏的铁砧','anvil',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (146,0,'陷阱箱','trapped_chest',1200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (147,0,'测重压力板（轻质）','light_weighted_pressure_plate',1600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (148,0,'测重压力板（重质）','heavy_weighted_pressure_plate',1000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (151,0,'阳光传感器','daylight_detector',5250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (152,0,'红石块','redstone_block',1600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (153,0,'下界石英矿石','quartz_ore',1500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (154,0,'漏斗','hopper',3000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (155,0,'石英块','quartz_block',6500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (155,1,'錾制石英块','quartz_block',7200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (155,2,'竖纹石英块','quartz_block',7000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (156,0,'石英楼梯','quartz_stairs',10000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (157,0,'激活铁轨','activator_rail',550,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (158,0,'投掷器','dropper',450,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (159,0,'白色染色粘土','stained_hardened_clay',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (159,1,'橙色染色粘土','stained_hardened_clay',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (159,2,'品红色染色粘土','stained_hardened_clay',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (159,3,'淡蓝色染色粘土','stained_hardened_clay',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (159,4,'黄色染色粘土','stained_hardened_clay',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (159,5,'黄绿色染色粘土','stained_hardened_clay',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (159,6,'粉红色染色粘土','stained_hardened_clay',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (159,7,'灰色染色粘土','stained_hardened_clay',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (159,8,'淡灰色染色粘土','stained_hardened_clay',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (159,9,'青色染色粘土','stained_hardened_clay',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (159,10,'紫色染色粘土','stained_hardened_clay',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (159,11,'蓝色染色粘土','stained_hardened_clay',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (159,12,'棕色染色粘土','stained_hardened_clay',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (159,13,'绿色染色粘土','stained_hardened_clay',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (159,14,'红色染色粘土','stained_hardened_clay',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (159,15,'黑色染色粘土','stained_hardened_clay',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (160,0,'白色染色玻璃板','stained_glass_pane',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (160,1,'橙色染色玻璃板','stained_glass_pane',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (160,2,'品红色染色玻璃板','stained_glass_pane',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (160,3,'淡蓝色染色玻璃板','stained_glass_pane',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (160,4,'黄色染色玻璃板','stained_glass_pane',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (160,5,'黄绿色染色玻璃板','stained_glass_pane',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (160,6,'粉红色染色玻璃板','stained_glass_pane',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (160,7,'灰色染色玻璃板','stained_glass_pane',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (160,8,'淡灰色染色玻璃板','stained_glass_pane',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (160,9,'青色染色玻璃板','stained_glass_pane',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (160,10,'紫色染色玻璃板','stained_glass_pane',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (160,11,'蓝色染色玻璃板','stained_glass_pane',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (160,12,'棕色染色玻璃板','stained_glass_pane',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (160,13,'绿色染色玻璃板','stained_glass_pane',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (160,14,'红色染色玻璃板','stained_glass_pane',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (160,15,'黑色染色玻璃板','stained_glass_pane',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (161,0,'金合欢树叶','leaves2',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (161,1,'深色橡树树叶','leaves2',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (162,0,'金合欢木','log2',160,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (162,1,'深色橡木','log2',160,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (163,0,'金合欢楼梯','acacia_stairs',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (164,0,'深色橡木楼梯','dark_oak_stairs',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (165,0,'粘液块','slime',1500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (166,0,'屏障','barrier',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (167,0,'铁活板门','iron_trapdoor',2000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (168,0,'海晶石','prismarine',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (168,1,'海晶石砖','prismarine',12000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (168,2,'暗海晶石','prismarine',10000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (169,0,'海晶灯','sea_lantern',12500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (170,0,'干草块','hay_block',800,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (171,0,'地毯','carpet',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (171,1,'橙色地毯','carpet',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (171,2,'品红色地毯','carpet',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (171,3,'淡蓝色地毯','carpet',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (171,4,'黄色地毯','carpet',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (171,5,'黄绿色地毯','carpet',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (171,6,'粉红色地毯','carpet',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (171,7,'灰色地毯','carpet',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (171,8,'淡灰色地毯','carpet',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (171,9,'青色地毯','carpet',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (171,10,'紫色地毯','carpet',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (171,11,'蓝色地毯','carpet',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (171,12,'棕色地毯','carpet',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (171,13,'绿色地毯','carpet',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (171,14,'红色地毯','carpet',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (171,15,'黑色地毯','carpet',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (172,0,'硬化粘土','hardened_clay',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (173,0,'煤炭块','coal_block',3000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (174,0,'浮冰','packed_ice',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (175,0,'向日葵','double_plant',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (175,1,'丁香','double_plant',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (175,2,'高草丛','double_plant',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (175,3,'大型蕨','double_plant',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (175,4,'玫瑰丛','double_plant',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (175,5,'牡丹','double_plant',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (179,0,'红沙石','red_sandstone',180,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (180,0,'红沙石楼梯','red_sandstone_stairs',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (182,0,'红沙石台阶','stone_slab2',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (183,0,'云杉木栅栏门','spruce_fence_gate',250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (184,0,'白桦木栅栏门','birch_fence_gate',250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (185,0,'丛林木栅栏门','jungle_fence_gate',250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (186,0,'深色橡木栅栏门','dark_oak_fence_gate',250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (187,0,'金合欢栅栏门','acacia_fence_gate',250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (188,0,'云杉木栅栏','spruce_fence',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (189,0,'白桦木栅栏','birch_fence',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (190,0,'丛林木栅栏','jungle_fence',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (191,0,'深色橡木栅栏','dark_oak_fence',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (192,0,'金合欢栅栏','acacia_fence',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (256,0,'铁锹','iron_shovel',600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (257,0,'铁镐','iron_pickaxe',2100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (258,0,'铁斧','iron_axe',2100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (259,0,'打火石','flint_and_steel',650,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (260,0,'苹果','apple',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (261,0,'弓','bow',240,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (262,0,'箭','arrow',250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (263,0,'煤炭','coal',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (263,1,'木炭','coal',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (264,0,'钻石','diamond',1200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (265,0,'铁锭','iron_ingot',480,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (266,0,'金锭','gold_ingot',750,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (267,0,'铁剑','iron_sowrd',1050,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (268,0,'木剑','wooden_sword',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (269,0,'木锹','wooden_shovel',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (270,0,'木镐','wooden_pickaxe',250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (271,0,'木斧','wooden_axe',250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (272,0,'石剑','stone_sword',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (273,0,'石锹','stone_shovel',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (274,0,'石镐','stone_pickaxe',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (275,0,'石斧','stone_axe',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (276,0,'钻石剑','diamond_sword',2500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (277,0,'钻石锹','diamond_shovel',1350,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (278,0,'钻石稿','diamond_pickaxe',3750,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (279,0,'钻石斧','diamond_axe',3750,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (280,0,'木棍','stick',30,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (281,0,'碗','bowl',40,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (282,0,'蘑菇煲','mushroom_stew',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (283,0,'金剑','golden_sword',1600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (284,0,'金锹','golden_shovel',900,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (285,0,'金镐','golden_pickaxe',2400,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (286,0,'金斧','golden_axe',2400,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (287,0,'线','string',40,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (288,0,'羽毛','feather',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (289,0,'火药','gunpowder',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (290,0,'木锄','wooden_hoe',180,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (291,0,'石锄','stone_hoe',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (292,0,'铁锄','iron_hoe',1050,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (293,0,'钻石锄','diamond_hoe',2500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (294,0,'金锄','golden_hoe',1600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (295,0,'小麦种子','wheat_seeds',60,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (296,0,'小麦','wheat',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (297,0,'面包','bread',250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (298,0,'皮革头盔','leather_helmet',600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (299,0,'皮革胸甲','leather_chestplate',1000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (300,0,'皮革裤子','leather_leggings',800,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (301,0,'皮革靴子','leather_boots',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (302,0,'锁链头盔','chainmail_helmet',1250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (303,0,'锁链胸甲','chainmail_chestplate',2000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (304,0,'锁链护腿','chainmail_leggings',1800,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (305,0,'锁链靴子','chainmail_boots',1000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (306,0,'铁头盔','iron_helmet',2500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (307,0,'铁胸甲','iron_chestplate',4000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (308,0,'铁护腿','iron_leggings',3500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (309,0,'铁靴子','iron_boots',2000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (310,0,'钻石头盔','diamond_helmet',6300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (311,0,'钻石胸甲','diamond_chestplate',10000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (312,0,'钻石护腿','diamond_leggings',8750,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (313,0,'钻石靴子','diamond_boots',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (314,0,'金头盔','golden_helmet',3750,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (315,0,'金胸甲','golden_chestplate',6000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (316,0,'金护腿','golden_leggings',5500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (317,0,'金靴子','golden_boots',3000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (318,0,'燧石','flint',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (319,0,'生猪排','porkchop',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (320,0,'熟猪排','cooked_porkchop',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (321,0,'画','painting',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (322,0,'金苹果','golden_apple',1000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (322,1,'金苹果','golden_apple',60000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (323,0,'告示牌','sign',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (324,0,'橡木门','wooden_door',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (325,0,'桶','bucket',1500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (326,0,'水桶','water_bucket',1600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (327,0,'岩浆桶','lava_bucket',1800,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (328,0,'矿车','minecart',2500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (329,0,'鞍','saddle',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (330,0,'铁门','iron_door',1000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (331,0,'红石','redstone',160,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (332,0,'雪球','snowball',20,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (333,0,'船','boat',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (334,0,'皮革','leather',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (335,0,'牛奶','milk_bucket',1750,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (336,0,'红砖','brick',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (337,0,'粘土','clay_ball',50,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (338,0,'甘蔗','reeds',60,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (339,0,'纸','paper',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (340,0,'书','book',400,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (341,0,'粘液球','slime_ball',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (342,0,'运输矿车','chest_minecart',3200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (343,0,'动力矿车','furnace_minecart',3000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (344,0,'鸡蛋','egg',100,16);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (345,0,'指南针','compass',2250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (346,0,'钓鱼竿','fishing_rod',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (347,0,'钟','clock',3250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (348,0,'萤石粉','glowstone_dust',70,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (349,0,'生鱼','fish',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (349,1,'生鲑鱼','fish',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (349,2,'小丑鱼','fish',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (349,3,'河豚','fish',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (350,0,'熟鱼','cooked_fish',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (350,1,'熟鲑鱼','cooked_fish',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (351,0,'墨囊','dye',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (351,1,'玫瑰红','dye',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (351,2,'仙人掌绿','dye',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (351,3,'可可豆','dye',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (351,4,'青金石','dye',180,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (351,5,'紫色染料','dye',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (351,6,'青色染料','dye',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (351,7,'淡灰色染料','dye',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (351,8,'灰色染料','dye',160,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (351,9,'粉红色染料','dye',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (351,10,'黄绿色染料','dye',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (351,11,'蒲公英黄','dye',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (351,12,'淡蓝色染料','dye',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (351,13,'品红色染料','dye',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (351,14,'橙色染料','dye',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (351,15,'骨粉','dye',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (352,0,'骨头','bone',270,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (353,0,'糖','sugar',80,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (354,0,'蛋糕','cake',1500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (355,0,'床','bed',400,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (356,0,'红石中继器','repeater',900,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (357,0,'曲奇','cookie',40,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (358,0,'地图（4*4/125）','filled_map',3200,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (358,1,'地图（2*2/251）','filled_map',4000,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (358,2,'地图（1*1/503）','filled_map',4800,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (358,3,'地图（0.5*0.5/1007）','filled_map',5600,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (358,4,'地图（0.25*0.25/2015）','filled_map',6400,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (359,0,'剪刀','shears',1000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (360,0,'西瓜','melon',20,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (361,0,'西瓜种子','melon_seeds',30,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (361,1,'南瓜种子','pumpkin_seeds',40,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (363,0,'生牛肉','beef',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (364,0,'牛排','cooked_beef',350,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (365,0,'生鸡肉','chicken',250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (366,0,'熟鸡肉','cooked_chicken',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (367,0,'腐肉','rotten_flesh',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (368,0,'末影珍珠','ender_pearl',400,16);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (369,0,'烈焰棒','blaze_rod',450,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (370,0,'恶魂之泪','ghast_tear',600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (371,0,'金粒','gold_nugget',90,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (372,0,'地狱疣','nether_wart',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (373,0,'水瓶','potion',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (374,0,'玻璃瓶','glass_bottle',100,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (375,0,'蜘蛛眼','spider_eye',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (376,0,'发酵蛛眼','fermented_spider_eye',350,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (377,0,'烈焰粉','blaze_powder',240,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (378,0,'岩浆膏','magma_cream',420,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (379,0,'酿造台','brewing_stand',600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (380,0,'炼药锅','cauldron',3000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (381,0,'末影之眼','ender_eye',750,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (382,0,'闪烁的西瓜','speckled_melon',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,50,'生成-爬行者','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,51,'生成-骷髅','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,52,'生成-蜘蛛','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,54,'生成-僵尸','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,55,'生成-史莱姆','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,56,'生成-僵尸猪人','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,57,'生成-恶魂','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,58,'生成-末影人','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,59,'生成-洞穴蜘蛛','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,60,'生成-蠹虫','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,61,'生成-烈焰人','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,62,'生成-岩浆怪','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,65,'生成-蝙蝠','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,66,'生成-女巫','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,67,'生成-末影螨','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,68,'生成-守卫者','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,90,'生成-猪','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,91,'生成-羊','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,92,'生成-牛','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,93,'生成-鸡','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,94,'生成-鱿鱼','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,95,'生成-狼','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,96,'生成-哞菇','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,97,'生成-雪傀儡','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,98,'生成-豹猫','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,99,'生成-铁傀儡','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,100,'生成-马','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,101,'生成-兔子','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (383,120,'生成-村民','spawn_egg',5000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (384,0,'附魔之瓶','experience_bottle',500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (385,0,'火焰弹','fire_charge',250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (386,0,'书与笔','writable_book',600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (387,0,'成书','written_book',650,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (388,0,'绿宝石','emerald',1350,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (389,0,'物品展示框','item_frame',360,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (390,0,'花盆','flower_pot',320,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (391,0,'胡萝卜','carrot',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (392,0,'马铃薯','potato',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (393,0,'烤马铃薯','baked_potato',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (394,0,'毒马铃薯','poisonous_potato',180,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (395,0,'空地图','map',3000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (396,0,'金萝卜','golden_carrot',900,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (397,0,'骷髅头颅','skull',300,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (398,0,'萝卜钓竿','carrot_on_a_stick',350,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (399,0,'下界之星','nether_star',1500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (400,0,'南瓜派','pumpkin_pie',320,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (401,0,'烟花火箭','fireworks',0,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (402,0,'烟火之星','firework_charge',0,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (403,0,'附魔书','enchanted_book',0,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (404,0,'红石比较器','comparator',2750,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (405,0,'地狱砖','netherbrick',180,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (406,0,'下界石英','quartz',1600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (407,0,'TNT矿车','tnt_minecart',3600,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (408,0,'漏斗矿车','hopper_minecart',5750,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (409,0,'海晶碎片','prismarine_shard',1200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (410,0,'海晶砂粒','prismarine_crystals',1500,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (411,0,'生兔肉','rabbit',150,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (412,0,'熟兔肉','cooked_rabbit',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (413,0,'兔肉煲','rabbit_stew',700,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (414,0,'兔子腿','rabbit_foot',30,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (415,0,'兔子皮','rabbit_hide',20,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (416,0,'盔甲架','armor_stand',250,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (417,0,'铁马铠','iron_horse_armor',3000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (418,0,'金马铠','golden_horse_armor',4200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (419,0,'钻石马铠','diamond_horse_armor',6750,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (420,0,'拴绳','lead',160,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (421,0,'命名牌','name_tag',200,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (422,0,'命令方块矿车','command_block_minecart',8000,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (423,0,'生羊肉','mutton',180,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (424,0,'熟羊肉','cooked_mutton',240,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (425,0,'白色旗帜','banner',1250,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (425,1,'黑色旗帜','banner',1250,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (425,2,'红色旗帜','banner',1250,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (425,3,'绿色旗帜','banner',1250,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (425,4,'棕色旗帜','banner',1250,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (425,5,'蓝色旗帜','banner',1250,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (425,6,'紫色旗帜','banner',1250,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (425,7,'青色旗帜','banner',1250,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (425,8,'淡灰色旗帜','banner',1250,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (425,9,'灰色旗帜','banner',1250,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (425,10,'粉红色旗帜','banner',1250,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (425,11,'黄绿色旗帜','banner',1250,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (425,12,'黄色旗帜','banner',1250,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (425,13,'淡蓝色旗帜','banner',1250,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (425,14,'品红色旗帜','banner',1250,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (425,15,'橙色旗帜','banner',1250,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (427,0,'云杉木门','spruce_door',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (428,0,'白桦木门','brich_door',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (429,0,'丛林木门','jungle_door',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (430,0,'金合欢木门','acacia_door',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (431,0,'深色橡木门','dark_oak_door',120,64);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (2256,0,'音乐唱片（C418-13)','record_13',500,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (2257,0,'音乐唱片（C418-cat)','record_cat',500,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (2258,0,'音乐唱片（C418-blocks)','record_blocks',500,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (2259,0,'音乐唱片（C418-chirp)','record_chirp',500,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (2260,0,'音乐唱片（C418-far)','record_far',500,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (2261,0,'音乐唱片（C418-mall)','record_mall',500,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (2262,0,'音乐唱片（C418-mellohi)','record_mellohi',500,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (2263,0,'音乐唱片（C418-stal)','record_stal',500,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (2264,0,'音乐唱片（C418-strad)','record_strad',500,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (2265,0,'音乐唱片（C418-ward)','record_ward',500,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (2266,0,'音乐唱片（C418-11)','record_11',500,1);
INSERT INTO `tb_shop_item` (`first_id`,`second_id`,`name`,`english_name`,`price`,`group_amount`) VALUES (2267,0,'音乐唱片（C418-wait)','record_wait',500,1);
